# Global parameters 
global:
    n_events: 1000 #5000                                                # Number of events to simulate
    rndseed: 12345                                                      # Random seed
    event_dir: ${HEP_DATA}/events_belle2_vtx_trigger                    # Path to events
    graph_dir: ${HEP_DATA}/hitgraphs_belle2_vtx_trigger                 # Path to hit graphs
    tracker_config: ${XTRACKER_CONFIG_PATH}                             # Path to tracker config

# basf2 MC trackfinder params 
mctrackfinder:
    UseCDCHits: False
    UseSVDHits: False
    UsePXDHits: False
    UseVTXHits: True
    WhichParticles: ['VTX',] # ['primary']  
    UseNLoops:  1.0 
    discardAuxiliaryHits: True
    UseSecondCDCHits: False
    #UseReassignedHits: False
    Smearing: False
    MinimalNDF: 6
    RecoTracksStoreArrayName: MCRecoTracks
        
# Event data selection cuts 
event_cuts: 
    UseCDCHits: False
    UseSVDHits: False
    UsePXDHits: False
    UseVTXHits: True
    OffsetVTX: -1
    OffsetPXD: -1
    OffsetSVD: 0
    OffsetCDC: 5

# Hit graph building configuration
selection:
    n_det_layers: 5
    pt_min: 0. # GeV
    phi_slope_max: 0.2
    z0_max: 100
    n_phi_sections: 1 
    n_eta_sections: 1 
    eta_range: [-5, 5]
    segment_type: all
    feature_scale_r: 15.0
    feature_scale_phi: 1.0
    feature_scale_z: 50.0
    feature_scale_t: 1.0
    useMC: False 


# Training configuration
training:
    numIters: 480               # Number of training iterations 
    numEps: 40                  # Number of new games to simulate during a new iteration.
    maxlenOfQueue: 200000       # Number of new game examples (per iteration) to train the neural networks.
    arenaCompare: 200           # Number of games to played in arena for network evaluation 
    checkpoint: ${HEP_DATA}/model_vtx_trigger/
    load_model: False
    load_folder_file: !!python/tuple ["${HEP_DATA}/model_vtx_trigger/","best.pth.tar"]
    numItersForTrainExamplesHistory: 2 

model: 
    nIter: 20
    verbose: False 
    mid_steps: 4
    noise_sigma: 0.0  
    update_e: False 
    useMC: False

optimizer:
    name: Adam 
    lr: 0.0001
    epochs: 1
    batch_size: 1

data: 
    name: hitgraphs
    n_train: 800
    n_valid: 200
    batch_size: 1  
