# Input/output configuration
input_dir: ${HEP_DATA}/events_belle2_vtxonly
output_dir: ${HEP_DATA}/hitgraphs_belle2_vtxonly

n_events: 20000

# Graph building configuration
selection:
    n_det_layers: 5
    pt_min: 0. # GeV
    phi_slope_max: 2.1
    z0_max: 100
    n_phi_sections: 1 
    n_eta_sections: 1 
    eta_range: [-5, 5]
    segment_type: all
    feature_scale_r: 15.0
    feature_scale_phi: 1.0
    feature_scale_z: 50.0
