# Output configuration
output_dir: ${HEP_DATA}/events_belle2_vtxonly

# Number of events to simulate 
n_events: 6000

# Random seed
rndseed: 12345 

# MC trackfinder settings 
mctrackfinder:
    UseCDCHits: False
    UseSVDHits: False
    UsePXDHits: False
    UseVTXHits: True
    WhichParticles: ['VTX'] # ['primary']  
    UseNLoops:  1.0  # 0.5
    discardAuxiliaryHits: True
    Smearing: False
    MinimalNDF: 6
    RecoTracksStoreArrayName: MCRecoTracks
